#!/bin/sh

DAEMON=/home/root/uz7ev-evcc-factest-launcher.sh
#This script launches the application that will blink an LED mapped to
#the Zynq or ZynqMP PS MIO
#In this case the PS LED is mapped to MIO26
DAEMON_OPTS=

start ()
{
echo " Starting UltraZed-EV Factory Test"
#    start-stop-daemon -S -o --background -x $DAEMON -- $DAEMON_OPTS
    start-stop-daemon -S -o -x $DAEMON -- $DAEMON_OPTS
}

stop ()
{
    echo " Stopping UltraZed-EV Factory Test"
    start-stop-daemon -K -x $DAEMON
}

restart()
{
    stop
    start
}

[ -e $DAEMON ] || exit 1
    case "$1" in
        start)
            start; ;;
        stop)
            stop; ;;
        restart)
            restart; ;;
        *)
            echo "Usage: $0 {start|stop|restart}"
            exit 1

esac
exit $?
