IMAGE_INSTALL_append = " peekpoke"
IMAGE_INSTALL_append = " gpio-demo"
IMAGE_INSTALL_append = " tricube"
IMAGE_INSTALL_append = " trd-files"
IMAGE_INSTALL_append = " trd-files-dev"
IMAGE_INSTALL_append = " packagegroup-trd"
IMAGE_INSTALL_append = " packagegroup-trd-dev"
