IMAGE_INSTALL_append = " peekpoke"
IMAGE_INSTALL_append = " gpio-demo"
IMAGE_INSTALL_append = " blinky"
IMAGE_INSTALL_append = " blinky-init"
IMAGE_INSTALL_append = " iperf"
IMAGE_INSTALL_append = " iperf3"
IMAGE_INSTALL_append = " bonnie++"

IMAGE_INSTALL_append = " mac-eeprom-config"
IMAGE_INSTALL_append = " mac-eeprom-config-init"
